"""All 35 literature-review rows, derived from research_paper_final.docx (Sections 2.1.1-2.1.7).

Each row matches the existing slide table schema:
  Sl. No. | Author & Year | Methods / Techniques | Dataset | Research Outcomes | Findings (relevance)
"""

ROWS = [
    # --- Surveys and overviews (Section 2.1.1) ---
    ("1", "Ariai & Demartini (2024)",
     "Comprehensive survey of legal NLP",
     "Synthesis of 131 prior studies",
     "Covers legal NER, classification, summarisation and legal LMs",
     "Touches nearly every component of our pipeline"),
    ("2", "Survey Authors (2025)",
     "Survey of contract-classification approaches",
     "14 English-language contract datasets",
     "Taxonomy of traditional ML, deep learning and transformer methods",
     "Justifies fine-tuning a compact domain model"),
    ("3", "Survey Authors (2025)",
     "Survey on legal summarisation",
     "Catalogues legal summarisation datasets",
     "Methods, datasets and evaluation metrics for legal summarisation",
     "Informs the intent-rewriting module's metric design"),
    ("4", "Ganguly et al. (2023)",
     "Review of legal NER and sentence boundary detection",
     "Legal-NLP literature",
     "Documents long-standing difficulty of NER and segmentation in legal text",
     "Motivates our rule-augmented segmentation and NER design"),

    # --- Foundation models (Section 2.1.2) ---
    ("5", "Devlin et al. (2019)",
     "Bidirectional transformer pre-training (BERT)",
     "BooksCorpus + English Wikipedia",
     "General-purpose language understanding backbone",
     "Backbone architecture for Legal-BERT (planned classifier)"),
    ("6", "Chalkidis et al. (2020)",
     "Domain pre-training of BERT on legal text (LEGAL-BERT)",
     "Legislation, case law and contracts",
     "Stronger legal-domain understanding than vanilla BERT",
     "Selected as the planned clause classifier (nlpaueb/legal-bert-base-uncased)"),
    ("7", "Sanh et al. (2019)",
     "Knowledge distillation of BERT (DistilBERT)",
     "Distilled from BERT-base",
     "~40% fewer parameters, ~60% faster, ~97% of accuracy",
     "Lighter alternative suitable for resource-constrained fine-tuning"),

    ("8", "Raffel et al. (2020)",
     "Unified text-to-text transformer (T5)",
     "C4 (Colossal Clean Crawled Corpus)",
     "Single seq2seq model for many NLP tasks",
     "Motivates choice of FLAN-T5-small for clause rewriting"),
    ("9", "Chung et al. (2022)",
     "Instruction fine-tuning (FLAN)",
     "1.8K instruction-tuning tasks",
     "Stronger zero-shot and few-shot performance across tasks",
     "Underpins the planned FLAN-T5 rewriter"),
    ("10", "Lewis et al. (2020)",
     "Denoising seq2seq pre-training (BART)",
     "Same pre-training data as RoBERTa",
     "Strong results on generation and comprehension",
     "Retained as an alternative rewriter architecture"),
    ("11", "Hendrycks et al. (2021)",
     "Expert annotation; QA-style contract review (CUAD)",
     "510 commercial contracts, 13,000+ spans",
     "41 expert-defined clause categories",
     "Primary training and evaluation dataset for our classifier"),
    ("12", "Cost-Benefit Analysis Study (2024)",
     "Comparison of shallow, deep and generative models",
     "CUAD single-label benchmark",
     "Fine-tuned DeBERTa 87.8% vs zero-shot GPT-4 67.2%",
     "Empirically validates fine-tuning a compact domain model over general LLM"),
    ("13", "Koreeda & Manning (2021)",
     "Document-level NLI for contracts (ContractNLI)",
     "Span-level evidence annotations on contracts",
     "Benchmark for contract entailment with rationale spans",
     "Span-level evidence design influences our clause-trigger reporting"),
    ("14", "Wang et al. (2023)",
     "Expert annotation for merger agreements (MAUD)",
     "Merger-agreement contracts",
     "Domain-specific contract-understanding benchmark",
     "Informs taxonomy design and supplementary evaluation"),

    ("15", "ACORD Authors (2025)",
     "Retrieval benchmark for clause drafting (ACORD)",
     "Expert-annotated retrieval dataset",
     "Benchmark for clause-clause retrieval",
     "Future-work signal for retrieval-augmented rewriting"),
    ("16", "Deontic Modality Study (2023)",
     "Categorising obligations, permissions, prohibitions",
     "Contract clauses",
     "Deontic-modality categorisation framework",
     "Directly relevant to classification and risk-flagging"),
    ("17", "Cemri et al. (2022)",
     "Unsupervised simplification (lexical + sentence splitting)",
     "Legal-text corpora (no parallel data)",
     "Domain-specific simplification without parallel corpora",
     "Validates feasibility of simplification with limited paired data"),
    ("18", "Text Simplification Study (2024)",
     "Text-simplification system for contract review",
     "Legal contract excerpts",
     "Reduces postgraduate-level text to ~tenth-grade readability; F-K, FRE, SMOG, Dale-Chall evaluation",
     "Evaluation design adopted for our rewriter"),
    ("19", "Legal Lay Summarisation Study (2025)",
     "Lay summarisation with LLMs (LegalEase)",
     "LegalEase dataset",
     "Sub-domain data outperform generic legal data",
     "Reinforces our use of CUAD + curated seed data"),
    ("20", "Manor & Li (2019)",
     "Plain-English summarisation of contracts",
     "Online ToS / contract corpus",
     "Foundational plain-English summarisation results",
     "Foundational reference for the rewriting module"),
    ("21", "Lippi et al. (2019)",
     "ML detection of unfair clauses (CLAUDETTE)",
     "UNFAIR-ToS corpus",
     "Automated unfair-clause detection",
     "Informs the rule-based risk-flagging design"),

    ("22", "Ruas et al. (2021)",
     "Memory-augmented neural networks with legal rationales",
     "Consumer-contract unfairness corpus",
     "Explainable unfair-clause detection",
     "Inspires explainable, trigger-named risk flags"),
    ("23", "Abusive Clause Detection Study (2024)",
     "Transformer-based abusive-clause detector",
     "B2C contracts",
     "Production-deployable abusive-clause detection",
     "Benchmark for risk-flag precision/recall"),
    ("24", "Mitigating Unfairness Study (2023)",
     "LLM prompting + chain-of-thought for unfair clauses",
     "Consumer contract clauses",
     "CoT reasoning improves unfair-clause detection and mitigation",
     "Considered but rejected to keep risk flagging transparent"),
    ("25", "Contract Smells Study (2025)",
     "LLM detection of 'contract smells' (code-smell analogy)",
     "Commercial contracts",
     "Reframes contract risks as inspectable patterns",
     "Conceptual basis for trigger-named risk flagging"),
    ("26", "Wolf et al. (2020)",
     "Hugging Face Transformers library",
     "n/a (toolkit paper)",
     "Open-source state-of-the-art NLP toolkit",
     "Core dependency for fine-tuning and inference"),
    ("27", "Honnibal & Montani (2017)",
     "spaCy 2 NLP pipeline",
     "n/a (toolkit paper)",
     "Tokenisation, segmentation, NER infrastructure",
     "Used for clause segmentation and (planned) statistical NER"),
    ("28", "Smith (2007)",
     "Tesseract OCR engine",
     "n/a (system paper)",
     "Open-source OCR for printed documents",
     "Supports text extraction from scanned PDFs"),

    ("29", "Loshchilov & Hutter (2019)",
     "Decoupled weight-decay (AdamW)",
     "Standard NLP/vision benchmarks",
     "Improved regularisation for transformer fine-tuning",
     "Standard optimiser for our planned fine-tuning"),
    ("30", "Papineni et al. (2002)",
     "BLEU metric for MT evaluation",
     "n/a (metric paper)",
     "n-gram precision-based automated metric",
     "Planned automated metric for the rewriter"),
    ("31", "Lin (2004)",
     "ROUGE metric for summary evaluation",
     "n/a (metric paper)",
     "Recall-oriented automated metric",
     "Planned automated metric for the rewriter"),
    ("32", "Abadi et al. (2015)",
     "TensorFlow framework",
     "n/a (framework paper)",
     "Large-scale ML framework",
     "Reference framework (we use PyTorch via Transformers)"),
    ("33", "Chalkidis et al. (2021)",
     "LexGLUE benchmark suite",
     "Aggregated legal-NLP datasets",
     "Benchmark for legal language understanding in English",
     "Supplementary evaluation target"),
    ("34", "LEDGAR Dataset (2020)",
     "Large-scale multi-label contract classification (LEDGAR)",
     "Contract provisions from regulatory filings",
     "Large-scale provisions corpus",
     "Supplementary training data for the classifier"),
    ("35", "Vuthoo, Khetarpaul & Mishra (2026)",
     "Efficient clause identification using NLP + web-sourced data",
     "Contract corpora with web augmentation",
     "Methodology for scalable clause identification",
     "Methodology relevant to our segmentation stage"),
]

assert len(ROWS) == 35, len(ROWS)
